services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: edullm-admin-back:1.0
    container_name: admin-back-ms
    restart: unless-stopped

    user: "1001:1001"
    #Cambio para prod
    read_only: false
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
      - /app/tmp:rw,noexec,nosuid,size=32m    

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M

    networks:
      - default          # para comunicarse con qdrant
      - observability-net # para enviar trazas a Alloy
    
    #ports:
    #  - "8002:8002"  # mapea puerto host:contenedor
    
    volumes:
      - .:/app
      # Anonymous volume: evita que node_modules local sobrescriba el del contenedor
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:admin@host.docker.internal:5432/edu_llm?schema=comun
      - HOST=0.0.0.0
      - PORT=8002
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Opcional: para debugging (permite attach de debugger)
    # command: ["nodemon", "--inspect=0.0.0.0:9229", "server.js"]
    # ports:
    #   - "9229:9229"  # debugging port


networks:
  observability-net:
    external: true   